<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.13" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Tools\Tools.csproj" />
    <ProjectReference Include="..\Entity.Service.Application\Entity.Service.Application.csproj" />
  </ItemGroup>

</Project>
