CREATE TABLE [entity].[Tenants]
(
	[EntityId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[MoveInDate] DATETIME NOT NULL,
	[MoveOutDate] DATETIME NULL,

	--CONSTRAINTS	
	CONSTRAINT [FK_Tenants_EntityID] FOREIGN KEY (EntityID) REFERENCES [entity].[Entities](Id)
)
