<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entity.Service.Application\Entity.Service.Application.csproj" />
    <ProjectReference Include="..\Entity.Service.Domain\Entity.Service.Domain.csproj" />
  </ItemGroup>

</Project>
